In [12]:
import pandas as pd
import psycopg

conn_str = "dbname=SCHOOL user=postgres password=Nikhil@pgs host=localhost port=5432"

with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute("""
        SELECT
            student_id,
            first_name,
            last_name,
            gpa
        FROM
            students
        WHERE
            gpa > 3.5
        ORDER BY
            gpa DESC;
        """)
        rows=cur.fetchall()
        df = pd.DataFrame(rows,columns=['student_id','first_name','last_name','gpa'])
        display(df)

   student_id first_name last_name   gpa
0           8      Sanya     Gupta  4.00
1           3       Diya    Mishra  3.92
2          10       Mira     Reddy  3.88
3           1      Aarav    Sharma  3.85
4           6       Isha     Patel  3.78
5           4     Ananya     Joshi  3.65

In [14]:
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute("""
        SELECT * FROM students;
        """)
        rows=cur.fetchall()
        df = pd.DataFrame(rows)
        display(df)

    0        1       2   3     4           5
0   1    Aarav  Sharma  10  3.85  2025-06-01
1   2   Vivaan  Kapoor  11  3.20  2025-06-02
2   3     Diya  Mishra  10  3.92  2025-06-01
3   4   Ananya   Joshi  12  3.65  2024-06-01
4   5    Kabir   Mehta   9  3.40  2026-01-15
5   6     Isha   Patel  11  3.78  2025-06-01
6   7  Reyansh   Singh  12  2.95  2024-06-01
7   8    Sanya   Gupta  10  4.00  2025-06-03
8   9    Arjun   Verma   9  3.15  2026-01-16
9  10     Mira   Reddy  12  3.88  2024-06-02

Adding new table

In [17]:
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute("""
        CREATE TABLE clubs
        (
            club_id SERIAL PRIMARY KEY,
            club_name VARCHAR(100) NOT NULL,
            student_id INT 
        );
        """)
        conn.commit()

In [18]:
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute("""
        INSERT INTO clubs (club_id, student_id, club_name) VALUES
        (101, 1, 'Coding'),
        (102, 2, 'Chess'),
        (103, 3, 'Drama'),
        (104, 99, 'Robotics');
        """)
        conn.commit()

In [20]:
with psycopg.connect(conn_str) as conn:
    with conn.cursor() as cur:
        cur.execute("""
        SELECT * FROM clubs;
        """)
        df2=pd.DataFrame(cur.fetchall(), columns=['club_id', 'student_id', 'club_name'])
        display(df2)

   club_id student_id  club_name
0      101     Coding          1
1      102      Chess          2
2      103      Drama          3
3      104   Robotics         99